### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by svoip** [NicholasBellucci/SociableWeaver#45]
I learned how to install it, and how to map my types to Graphql queries or mutations. 
But how those queries can be then used in my app? I have not seen any queries being generated in the filesystem in order to Graphql (Apollo) library can pick them up during build.
Can you guide me please? If there is nothing yet of this kind, how can one manage it?
Thanks

**Comment by NicholasBellucci** [comment]
Essentially when you create the Weave object like this

```swift
let query = Weave(.query) {
     Field(Comment.CodingKeys.id)
}
```

You can then access the query string like this:

```swift
String(describing: query) // result: query { id }
```

That query string can then be posted to the API you are using. As for working with Apollo I am not super familiar but I assume they allow you to post a basic query string.

**Comment by svoip** [comment]
Thank you for response. I would like to ask these:
1) If not considered to use with a tool like Apollo, what was your intended use case for the library? How would one normally use it? I am just curious :).
2) Can I implement an integration with Apollo (known iOS tool for Graphql) and make a pull request?

**Comment by NicholasBellucci** [comment]
So the overall purpose of this library is to create a way for users to make GraphQL queries, in Swift, that look and feel more like GraphQL. That is why I use Swift's new Result Builder functionality. For GraphQL when you have a query all you really need to do is POST that query to an API to get a response. Apollo is not needed in order to do this. As for an integration with a pull request...I don't really want this library to be depended on Apollo as that framework is pretty large and the focus of this one is to keep it lightweight. I am more than available though to help with integrations if you have any more questions.

**Comment by svoip** [comment]
It is all clear. Thank you for this library.
